### ISSUE TITLE
Getting '400' error for uri having plus(%2B) symbol in it

### ISSUE THREAD

**Issue by sonaljeet** [rest-assured/rest-assured#1031]
I am hitting one URL having a plus symbol in it. A sample of the URL is given below:

https://api.digitalvault.cloud/<someText>/<someText>/samples?v=2.1&<someText>&startTime=2018-06-14T19:54:34%2b08:00&endTime=2018-06-14T01:54:34%2b08:00.
But it is giving 400 error as response. 

Below is my code:
RestAssured.given()
    .config(RestAssured.config().sslConfig(new SSLConfig().relaxedHTTPSValidation()))
    .header("Authorization", Authorization).header(HeaderParameter1, HeaderParameterValue1)
    .header(HeaderParameter2, HeaderParameterValue2).get(URI);
Where URI is the actual url.

**Comment by basdijkstra** [comment]
What happens when you explicitly turn off URL encoding?

https://github.com/rest-assured/rest-assured/wiki/Usage#url-encoding

**Comment by sonaljeet** [comment]
I am getting below exception:
java.lang.IllegalArgumentException: Illegal character in query at index 102 
when I set urlEncodingEnabled(false)

**Comment by basdijkstra** [comment]
Is this a URL that's accessible for everybody? I'd like to try it for myself. I see a couple of weird things in the URL as well (three consecutive forward slashes, double ampersand).

Also, do you have an example from a call that works? For example one that's sent by a UI, or something from documentation?

**Comment by sonaljeet** [comment]
This is the complete url:
https://api.digitalvault.cloud/timeseries/cep/samples?v=2.1&timeseries_ids=bb90bd8d-0d6d-450f-8399-f089cb09aa87&startTime=2018-06-19T06:55:32%2B08:00&endTime=2018-06-19T12:55:32%2B08:00&metric=HourlyAverage&orderby=timestamp asc

It is working fine when I hit the same service from postman.
Also, using RestAssured it works perfect after removing %2B. But I need %2b to be added in the URL as per my project requirement.

**Comment by basdijkstra** [comment]
1. What I don't understand is why you have _some_ characters that are URL encoded already (the + becoming %2B) but other characters that should be URL encoded are not yet encoded (the : should become %3A). That might cause some troubles here.

2. When I do this:
`given().urlEncodingEnabled(false).and().log().all().when().get("https://api.digitalvault.cloud/timeseries/cep/samples?v=2.1&timeseries_ids=bb90bd8d-0d6d-450f-8399-f089cb09aa87&startTime=2018-06-19T06:55:32%2B08:00&endTime=2018-06-19T12:55:32%2B08:00&metric=HourlyAverage&orderby=timestamp").then().log().all();`
I don't get that IllegalArgumentException. Could you post a snippet?

3. The fact that you _must_ have %2B in your URLs is a really weird project requirement. I think the project requirement should be 'we're able to hit the endpoint'. Either encode everything or encode nothing...

**Comment by sonaljeet** [comment]
Thanks a ton for your explanation!
I encoded all special characters. Below is my updated URL:
https%3A%2F%2Fapi.digitalvault.cloud%2Ftimeseries%2Fcep%2Fsamples%3Fv%3D2.1%26timeseries_ids%3Dbb90bd8d-0d6d-450f-8399-f089cb09aa87%26startTime%3D2018-06-19+06%3A55%3A32%2B08%3A00%26endTime%3D2018-06-19+12%3A55%3A32%2B08%3A00%26metric%3DHourlyAverage%26orderby%3Dtimestamp+asc

But, now I am getting different exception:
java.net.connectexception: connection refused: connect

Is this because I am sending the encoded URL? Please suggest.
Also, please do let me know if any other details are required from my side.

**Comment by basdijkstra** [comment]
Yes, that's because you send the encoded URL. It looks like REST Assured doesn't recognize this as an endpoint in itself anymore and appends it to the default uri (localhost) and port (8080). This is my output in the console:
`Request method:	GET
Request URI:	http://localhost:8080/https%253A%252F%252Fapi.digitalvault.cloud%252Ftimeseries%252Fcep%252Fsamples%253Fv%253D2.1%2526timeseries_ids%253Dbb90bd8d-0d6d-450f-8399-f089cb09aa87%2526startTime%253D2018-06-19%2B06%253A55%253A32%252B08%253A00%2526endTime%253D2018-06-19%2B12%253A55%253A32%252B08%253A00%2526metric%253DHourlyAverage%2526orderby%253Dtimestamp%2Basc
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		Accept=*/*`
Again, the easiest solution would be to not pre-encode the '+' characters at all and have REST Assured handle it all for you. Or is that _really_ not an option?

If so, you could try only pre-encoding ('by hand' as you did here) the characters that need escaping (I think only the '+' and the ':') and setting urlEncodingEnabled to false. That's already tricky, though (what happens if you get other characters that need escaping later on?)

**Comment by sonaljeet** [comment]
Thanks much for looking into the issue!
Now we decided not to include '+' in the URL and handling the timezone in a different way before hitting the server. 
Closing this issue.
