### ISSUE TITLE
Parameter for DELETE request is not passed

### ISSUE THREAD

**Issue by pwittchen** [rest-assured/rest-assured#1066]
Hi,

I try to perform the following test for `DELETE` method

```java
@Test
public void shouldDeleteAccount() {
  given()
    .parameter("number", "1")
    .when().delete("/account")
    .then().body("message", equalTo("account with number 1 deleted")).statusCode(200);
}
```

but it seems `parameter` named `number` is not passed to this request.
Similar test for `POST` method works fine.
Can you confirm that or show me correct usage of the library?

**Comment by pwittchen** [comment]
You're right! With `formParam(...)` it works fine. Thanks!
Nevertheless, it's a bit strange because for `post(...)` I'm using just `param(...)` and it works.

**Comment by johanhaleby** [comment]
Yeah, REST Assured tries to "guess" what kind of parameter to send when using an HTTP VERB. On DELETE it guesses that you want to use query parameters. On POST it will guess that you mean form param. It's probably better to be specific but there are several server side frameworks that doesn't care if the parameter is sent in the body or in the query string. Thus this can be reflected in the test as well by using "param" instead of explicit "queryParam" or "formParam".

**Comment by pwittchen** [comment]
Good to know that. I don't have much experience with this library, so I wasn't aware of implementations of these methods under the hood.

**Comment by pwittchen** [comment]
It makes sense. Actually, design of my API was wrong, where `DELETE` should take just one parameter and it could be in the path instead of form param. I already updated my API and test to use path param.
