### ISSUE TITLE
java.security.KeyStore cannot be loaded

### ISSUE THREAD

**Issue by reenigneEsrever92** [rest-assured/rest-assured#1252]
I'm trying the following:

```java
KeyStore ks = KeyStore.getInstance("PKCS12");
ks.load(new FileInputStream(new File("path-to.p12")), new char[] {'p', 'a', 's', 's'});

given().baseUri(System.getenv("rest-base-URL"))
                    .keyStore(ks)
```
but that doesn't seem to work.
The following is the result:
```bash
Error Message: groovy.lang.MissingMethodException: No signature of method: io.restassured.config.SSLConfig.keyStore() is applicable for argument types: (java.security.KeyStore) values: [java.security.KeyStore@3ea10d4a]
Possible solutions: keyStore(java.lang.String), keyStore(java.io.File, java.lang.String), keyStore(java.lang.String, java.lang.String), getKeyStore(), trustStore(java.security.KeyStore)
```

It's this snippet in `io.restassured.internal.RequestSpecificationImpl` that is problematic:
```java
RequestSpecification keyStore(KeyStore keyStore) {
  def sslConfig = restAssuredConfig().getSSLConfig()
  restAssuredConfig = restAssuredConfig().sslConfig(sslConfig.keyStore(keyStore)) // <-- results in MissingMethodException
  this
}
```

`io.restassured.internal.SSLConfig` does not seem to have the capability to set a KeyStore that way.
Not quite sure why it compiles though. 
I guess it's some mangling that's being done between groovy and java!?

**Comment by JOpsDev** [comment]
I ran into this requirement as well because I need to provide a self compiled KeyStore for the SSL connection. We need to compile the KeyStore ourselves because the keys are never stored in the file system and we need to authenticate mutually with certificates.
There is a workaround described [here](https://stackoverflow.com/a/37436519) which is a bit of a hack. The key part of the hack is doing this:
`RestAssured.config = RestAssured.config().sslConfig(config);`

So I think we would need io.restassured.config.SSLConfig.keyStore(KeyStore) analogous to the already existing io.restassured.config.SSLConfig.trustStore(KeyStore) .

**Comment by jozzan** [comment]
I was wondering if there are any tests for ssl connection. 
Could you point me to some?

**Comment by JOpsDev** [comment]
What kind of tests? 
The most well known for server side is https://www.ssllabs.com/ssltest/ for public available resources,
There are some scripts for openssl as well. And you will find more tools by googling for "ssltest".

**Comment by jozzan** [comment]
Well I've implemented said method in SSLConfig and I would like to test it. 
The question is where would be the best place to do that and also is there a test already that is using an SSLConfig?
