### ISSUE TITLE
Add ability to remove contentType

### ISSUE THREAD

**Issue by johanhaleby** [rest-assured/rest-assured#1516]
This is surprisingly difficult, I don't even know how to do it myself of the top of my head.  This doesn't work:

```kotlin
filter { req, resp, ctx ->
    req.removeHeader(CONTENT_TYPE)
    ctx.next(req, resp)
}
```

RA will add the default header for post's if we remove. 

We should probably add `noContentType` explicitly to the API.

**Comment by johanhaleby** [comment]
I decided to call it "noContentType" instead

**Comment by dilhelh** [comment]
@johanhaleby, We can see in the documentation that when we define the body of a request with an object, this object is converted into json/xml. I expected that after this conversion happened, the content-type header would be updated correctly but unfortunately this is not happening. So I thought of disabling the default content-type so that it would be possible to add through a filter but that is also not possible because the content-type is being added (even calling RequestSpecBuilder's `noContentType` method). Am I doing something wrong or is there any possible improvement we should work on in Rest Assured?

In the code snippet bellow is set the `noContentType()` in RequestSpecBuilder. After, this builder is used to build a request. In the request we set the filter (to inspect all the request headers), the body (converted successfully from java object to json) and the HTTP method. After send a post, the filter shows that the Content-Type was set to the value `text/plain; charset=UTF-8`.

```java
//Request spec builder creating
RequestSpecBuilder builder = new RequestSpecBuilder();
builder.noContentType();
```

```java
//Using the spec in the requests
RestAssured.given(builder.build())
     .filter((req, resp, ctx) -> {
	req.getHeaders().asList().stream()
	    .forEach(System.out::println);     //Content-Type=text/plain; charset=UTF-8
	return ctx.next(req, resp);
    })
    .body(new UserCredentials(username, password))
    .post("/login")
    .then()
          .statusCode(200);
```
