### ISSUE TITLE
Possible to use this without "given/when/then" syntax?

### ISSUE THREAD

**Issue by thokari** [rest-assured/rest-assured#733]
I am really a big fan of the Spock testing framework and I wanted to use Spock's way of writing tests, and not use RA for the assertions. To lessen confusion for the reader I would like to completely avoid the given().when().then() syntx of RA, and only use the parts that deal with REST and not with testing. Could you provide examples or anything in that direction. Many thanks!

**Comment by johanhaleby** [comment]
What do you mean with "the parts that deal with REST"?

**Comment by thokari** [comment]
Basically HTTP, creating requests with all their configuration, dealing with authorization, getting response headers and content and so on.
I guess I just need to wrap my head around the API and only use the parts that I want.

E.g. (with Spock / Groovy):

```
given:
def requestSpec = RequestSpecification.with().parameters("firstName", "John", "lastName", "Doe");

when:
def response = requestSpec.get("/")

then:
response.body("greeting", equalTo("Greetings John Doe"));
```

I can't see how to get a "Reponse" from a "RequestSpecification", though.

**Comment by johanhaleby** [comment]
Ok, the flow in REST Assured essentially looks like this:

1. Defined a request specification (given)
1. Execute this specification (when)
1. Assert properties or values of the response using a response specification

The last part is optional since you can extract values from the response and use any other library you want to assert that values. But your example above looks essentially like the way you should go about (if I understand your question correctly). Maybe the more idiomatic way of building a `RequestSpecification` is to use a [RequestSpecBuilder](http://static.javadoc.io/io.rest-assured/rest-assured/3.0.0/io/restassured/builder/RequestSpecBuilder.html), for example:

```groovy
def requestSpec = new RequestSpecBuilder().addParam("", "). ...
```

But your example should be fine as well.

> I can't see how to get a "Reponse" from a "RequestSpecification", though.

You're doing it here:

```groovy
when:
def response = requestSpec.get("/")
```

The `response` here is of type `io.restassured.response.Response`

**Comment by thokari** [comment]
Sorry about the confusion!
I coded the example from the hip, without actually running it.
When looking at the documentation, I missed the 
"Methods inherited from interface io.restassured.specification.RequestSenderOptions"...
My bad.
