### ISSUE TITLE
Rest Assured not picking up proxy/non proxy setup up in maven setting file. 

### ISSUE THREAD

**Issue by SandyOnGithub** [rest-assured/rest-assured#760]
Hi Team,
Rest Assured not picking up proxy/non proxy setup up in maven setting file. I am manually putting it up using RestAssured.Proxy method and resetting it using RestAssured.reset().

I have to keep track of proxy for every call. Can RestAssured manage that looking it up from maven setting file. Or provide its own setting file or something.

Thanks!

**Comment by johanhaleby** [comment]
No it can't because that would couple REST Assured to maven. REST Assured is a library that should be possible to use from any build tool.

You can of course write something like this yourself and we could include it as a module (similar to the [json schema validator module](https://github.com/rest-assured/rest-assured/wiki/GettingStarted#json-schema-validation)) that is outside rest-assured core.
