### ISSUE TITLE
SSE Support?

### ISSUE THREAD

**Issue by victornoel** [rest-assured/rest-assured#796]
Hi,

I couldn't find anything about SSE in the documentation so I was wondering if it is a missing feature or if simply there is a way to test SSE based REST API with rest-assured that I couldn't find :)

If it's a missing feature, I don't think it would be very easy to implement but it could be quite interesting to have.
In particular, the following use case are of interest (to me, but I think to other people too):
 - asserting about one event verifying some constraints
 - asserting about all events verifying some constraints
 - asserting the above, taking into account order, or not!
 - asserting for only some event types
 - etc

These are some ideas, even the most basic way of testing things would be great :)

Thanks!

**Comment by johanhaleby** [comment]
Hi,

There's no built in way to do this. Not sure how much of an effort it'll be. I don't think SSE should be supported natively since due to it's request-response nature. One might be able to hack something up using [awaitility](http://www.awaitility.org) in combination with rest-assured? I will close this issue as "out-of-scope". But if you want to contribute with a module (like the json schema validation module) that would be very interesting.

/Johan

**Comment by victornoel** [comment]
Ok, thanks for the answer and ideas to combine it with awaitility!

**Comment by pawelebe** [comment]
@victornoel have you come with any solutions about SSE? thanks!

**Comment by victornoel** [comment]
@pawelebe not really, it was a long time ago, I believe I must have used the workaround proposed above ^^

**Comment by YohannParis** [comment]
Being able to test SSE would be an amazing feature.
