### ISSUE TITLE
JsonPath.getDouble truncates or rounds output

### ISSUE THREAD

**Issue by grzechol** [rest-assured/rest-assured#797]
The following code:
```java
public static void main(String[] args) {
   JsonPath jp = new JsonPath("{ \"value\" : 13353.750452, \"unit\" : \"kg\" }");
   double value = jp.getDouble("value");
   System.out.println(value);
}
```
Should print `13353.750452`
but it prints `13353.75` instead.

It seems to be non-deterministic how the output is being truncated: `13353.07050452` is returned as `13353.07`, and `13353.17530452` as `13353.176`

Tested with rest-assured 3.0.2 and Oracle Java 1.8.0_121

**Comment by johanhaleby** [comment]
See [JsonConfig](https://github.com/rest-assured/rest-assured/wiki/Usage#json-config), [note on floats and doubles](https://github.com/rest-assured/rest-assured/wiki/Usage#note-on-floats-and-doubles) and [this](https://github.com/rest-assured/rest-assured/issues/738) issue. Also java's floating point operatios are not strict (which is why you usually provide an error margin when testing for floats/doubles with for example assertj). I don't think there's anything REST Assured can do to improve this (but correct me if I'm mistaken).

**Comment by yamironova** [comment]
I decided this by JsonPathConfig


      import io.restassured.path.json.config.JsonPathConfig;

      JsonPathConfig cfg = new JsonPathConfig(JsonPathConfig.NumberReturnType.BIG_DECIMAL);
      BigDecimal bigDecimal  = given()........extract().
                jsonPath().
                using(cfg).
                get("name"); 
     Double myDouble = bigDecimal.doubleValue(); 

Now all 16 digit here!
