### ISSUE TITLE
(how to) Assert array on json response body contains element

### ISSUE THREAD

**Issue by dialex** [rest-assured/rest-assured#805]
The body response looks like:

```json
[
  {
    "userId": 123,
    "username": "sysadmin",
    "roles": [
      "ROLE_OPERATOR",
      "ROLE_ADMIN"
    ]
  }
]
```

I want to assert the `roles` array contains at least `"ROLE_ADMIN"`. So I wrote this test:

```java
RestAssured.given(...).get(...)
  .then()
    .statusCode(200)
  .and()
    .body("roles", hasItem("ROLE_ADMIN"));
```

But is fails saying:

```
java.lang.AssertionError: 1 expectation failed.
JSON path roles. doesn't match.
Expected: a collection containing "ROLE_ADMIN"
  Actual: [[ROLE_OPERATOR, ROLE_ADMIN]]
```

`hasItemInArray` also fails, but mentions `array` instead of `collection`.
What am I doing wrong?

**Comment by dialex** [comment]
This worked: `body("roles[0]", hasItem("ROLE_ADMIN"))`
I barely know why... this is not intuitive at all.

**However, now I want to assert also the length of the array.**
So I tried `body("roles[0]", hasSize(1))` and failed. Method `arrayWithSize` also failed... :disappointed:

**Comment by johanhaleby** [comment]
Hi, 

Please use the mailing list when asking questions in the future.

You return an array of json objects, this means that. So when you do:

```java
.body("roles", ...);
```

Rest Assured will return for the "roles" value (list) for ALL objects in the list. To put it in english it means "In the returned list, in each object return the value of 'roles'". I.e. it will return a list of lists since roles is also a list.

To clarify further imagine you have this JSON instead:

```json
[
  {
    "userId": 123,
    "username": "sysadmin",
    "roles": [
      "ROLE_OPERATOR",
      "ROLE_ADMIN"
    ]
  },
  {
    "userId": 124,
    "username": "something",
    "roles": [
      "ROLE_OPERATOR"
    ]
  }
]
```

`.body("roles", ...)` would now return:

```java
[[ROLE_OPERATOR, ROLE_ADMIN], [ROLE_OPERATOR]].
```

`[ROLE_OPERATOR, ROLE_ADMIN]` is the roles list for user 123 and `[ROLE_OPERATOR]` is the roles list for user 124.


What I suspect that you want to do is to validate that user 123 has the roles `ROLE_OPERATOR, ROLE_ADMIN`. You can do that by finding this user and then validate the roles:

```java
.body("find { it.userId == '123' }.roles", containsInAnyOrder("ROLE_OPERATOR", "ROLE_ADMIN")). ...
```

**Comment by johanhaleby** [comment]
> I want to assert the roles array contains at least "ROLE_ADMIN". So I wrote this test:

I think you can do like this:

```java
.body("roles", everyItem(hasItem("ROLE_ADMIN"));
```

**Comment by sahilmaggu** [comment]
How Can you find "userId": 124 has "username": "something". Please help...what will be the json path in this case

**Comment by keetron** [comment]
@johanhaleby 
I am going to be a nitwit on a closed item but 
`.body("roles", everyItem(hasItem("ROLE_ADMIN"));
`
should be 
`.body("roles", everyItem(hasItem("ROLE_ADMIN")));`

**Comment by johanhaleby** [comment]
Thanks, I've updated my comment

**Comment by mnmuniz** [comment]
can you share everyItem class please?

**Comment by mahon94** [comment]
where is "everyItem" class? how to import it?

**Comment by johanhaleby** [comment]
It's in "org.hamcrest.Matchers"

**Comment by AaryanRajesh** [comment]
Can someone give me an example to assert my GET request body response using body() method?
{
 "firstName": "Rest",
 "lastName": "Assured"
}

**Comment by keetron** [comment]
@AaryanRajesh This is not related to the original request and I would like to point out the other sources such as the wiki in this repo that has the answer: https://github.com/rest-assured/rest-assured/wiki/Usage#example-1---json
In your case: `body("fistName", equalTo("Rest")` etc

**Comment by cool102** [comment]
very useful
