### ISSUE TITLE
java REST Assured response body with Content-Type: text/html with injected html tags

### ISSUE THREAD

**Issue by myqqai** [rest-assured/rest-assured#950]
[https://stackoverflow.com/questions/38743055/java-rest-assured-response-body-with-content-type-text-html-with-injected-html](https://stackoverflow.com/questions/38743055/java-rest-assured-response-body-with-content-type-text-html-with-injected-html)

I met the same problem！

**Comment by johanhaleby** [comment]
Interesting :) Could you post the entire request and response (including headers) from e.g. Postman or wireshark? Impossible to debug this without more info.

**Comment by aivancioglo** [comment]
@johanhaleby This issue still persist. Will this bug be fixed soon?

**Comment by johanhaleby** [comment]
Help me out and reproduce it or better yet provide a pull request. It's superhard to fix problems that you don't experience yourself or don't know how to reproduce reliably.

**Comment by pencui** [comment]
I reproduced this problem: 
In rest assured, I log().all() the response:

HTTP/1.1 200 
X-Application-Context: mayon:testing:7001
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Date: Tue, 13 Nov 2018 13:38:38 GMT

<html>
  <body>{"code":"0","data":true,"message":"操作成功","success":true}</body>
</html>

the response body is html tag.

but this interface works fine when access with postman
![image](https://user-images.githubusercontent.com/7089076/48417082-d765a280-e78c-11e8-8483-b021bb37dd0b.png)

**Comment by pencui** [comment]
add screen shot for log().all() response:
![image](https://user-images.githubusercontent.com/7089076/48417593-12b4a100-e78e-11e8-98a8-482fb64f3635.png)

**Comment by sierisimo** [comment]
In addition to my previous comment. If I move my test from:

```
given(requestSpec)
                .`when`().post(Endpoints.Api.LOGIN)
                .then().contentType(ContentType.JSON)
                .and().assertThat().body(matchesJsonSchemaInClasspath("json/responses/auth/post_login-success.json"))
```

to:

```
given(requestSpec)
    .`when`().post(Endpoints.Api.LOGIN)
    .then().assertThat().body(matchesJsonSchemaInClasspath("json/responses/auth/post_login-success.json"))
```

The test works but I'm not able to check other things like a path inside of the body.

Actually a single call like:

```
given(requestSpec)
                .`when`().post(Endpoints.Api.LOGIN)
                .then().contentType(ContentType.JSON)
                .and().body("code", equalTo(200))
```

Shows the same error: 

```java
java.lang.AssertionError: 1 expectation failed.
Expected content-type "JSON" doesn't match actual content-type "text/html;charset=utf-8".
…
```
 
So I'm not sure if it's because of the request with form or what. 

Maybe useful, a single breakpoint in what is visible while running this test: 

<img width="1982" alt="imagen" src="https://user-images.githubusercontent.com/1699877/51019655-53882680-1541-11e9-86ec-3ddc7c2071a1.png">

**Comment by johanhaleby** [comment]
I suppose you want to specify the content type in the request? After `then` you switch to the `ResponseSpecification` which will assert that the contentType is JSON which you probably don't want in this case. You should instead do:

```kotlin
given(requestSpec)
                .contentType(ContentType.JSON)
.`when`().post(Endpoints.Api.LOGIN)                
                .body("code", equalTo(200))
```

**Comment by sierisimo** [comment]
Actually that's all the problem with this. That the **response** is actually a JSON and the headers include this information. But somehow rest-assured changes it to `text/html;charset=utf-8` without reason.

I don't want to send a JSON in my request, I'm sending a `application/x-www-form-urlencoded`
But if I want to check that the **response** is a JSON or if the body matches my JSON schema… it fails because **rest-assured** changed the Response content-type magically.

**Comment by mcocosila** [comment]
Hi Pencui,

Assuming you or someone still experiences the issue reported in this thread.

First of all, please check the Headers tab for your Postman response. I expect it to be text/html. Postman auto detects that the actual response content is JSON even if the content-type header is text/html. Therefore Postman renders the response body as JSON document.

REST-assured displays the api response strictly obeying the content-type directive, which is correct behavior. 

You need to declare that you need your HTML response to be interpreted as JSON. Even better, if in your control, you should ensure that the API itself sets the application/json content type on responses.

In order to fix your situation, in your REST-assured setup method do this:
`
RestAssured.registerParser("text/html", Parser.JSON);
`

Going forward you won't see responses like:
```
<html>
  <body>This is you JSON content</body>
</html>
```
You should see just:
`
This is you JSON content
`

**Comment by willfolsom** [comment]
If you're using Jupiter, you can do this:

```
// import io.restassured.RestAssured;
// import org.junit.jupiter.api.BeforeAll;

@BeforeAll
static void setup() {
     RestAssured.registerParser("text/html", Parser.JSON);
}
```

and it covers it for every test in the file.
